packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@antfu/eslint-config': ^5.2.2
  '@turbo/gen': ^2.6.3
  '@types/node': ^22.10.2
  '@vitest/coverage-v8': ^3.2.4
  eslint: ^9.35.0
  eslint-plugin-format: ^1.0.1
  tsdown: ^0.14.2
  tsx: ^4.19.2
  typescript: ^5.9.2
  vitest: ^3.2.4
